//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeerFlow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageInfo
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ContentType { get; set; }
        public System.DateTime ExifDate { get; set; }
        public string ExifLattitude { get; set; }
        public string ExifLongitude { get; set; }
        public string StorageType { get; set; }
        public Nullable<int> ImageId { get; set; }
    
        public virtual Image Image { get; set; }
    }
}
